---
Resources:
  SNS03120D65:
    Type: AWS::SNS::Topic
    Metadata:
      aws:cdk:path: ExampleLambdaSnsStack/SNS/Resource
  FanoutServiceRoleDABDF464:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    Metadata:
      aws:cdk:path: ExampleLambdaSnsStack/Fanout/ServiceRole/Resource
  FanoutServiceRoleDefaultPolicy510DD604:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action: sqs:SendMessage
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - FanoutDeadLetterQueueDAFF220E
            - Arn
        - Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
          Effect: Allow
          Resource: "*"
        - Action: sns:Publish
          Effect: Allow
          Resource:
            Ref: SNS03120D65
        Version: '2012-10-17'
      PolicyName: FanoutServiceRoleDefaultPolicy510DD604
      Roles:
      - Ref: FanoutServiceRoleDABDF464
    Metadata:
      aws:cdk:path: ExampleLambdaSnsStack/Fanout/ServiceRole/DefaultPolicy/Resource
  FanoutDeadLetterQueueDAFF220E:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ExampleLambdaSnsStack/Fanout/DeadLetterQueue/Resource
  Fanout5E42E65D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: redacted
        S3Key: redacted
      Role:
        Fn::GetAtt:
        - FanoutServiceRoleDABDF464
        - Arn
      DeadLetterConfig:
        TargetArn:
          Fn::GetAtt:
          - FanoutDeadLetterQueueDAFF220E
          - Arn
      Environment:
        Variables:
          TOPIC_ARN:
            Ref: SNS03120D65
      Handler: com.example.fanout.Handler
      MemorySize: 512
      Runtime: java11
      Timeout: 10
      TracingConfig:
        Mode: Active
    DependsOn:
    - FanoutServiceRoleDefaultPolicy510DD604
    - FanoutServiceRoleDABDF464
    Metadata:
      aws:cdk:path: ExampleLambdaSnsStack/Fanout/Resource
      aws:asset:path: asset.ded6eb96f57d3cfd574d1c27fc3c0688853a1c9f8746d7a2483a4d21a49381fa.jar
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWPzQ6CMBCEn8V7WQUPnsXEgydF72QplaxAq2yrMU3f3VLiab6Z3exPAUUO+Qo/nMm2zwZqwF8tyl7EqPasGfzNPEmKw10nCGLAsWkR/NFpacnoufTnIAhH8JUZ1BwnPZuB5He2CwXB2xqZlWXYzxI9lE72ypbISvArLr045dKIBCGI1BlP60h3abRi4yapgjjhG9f5DjbxkQcTZZPTlkYF1aI/j2JxquQAAAA=
    Metadata:
      aws:cdk:path: ExampleLambdaSnsStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/cdk-bootstrap/hnb659fds/version"
    Description: Version of the CDK Bootstrap resources in this environment, automatically
      retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
    - Assert:
        Fn::Not:
        - Fn::Contains:
          - - '1'
            - '2'
            - '3'
            - '4'
            - '5'
          - Ref: BootstrapVersion
      AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap'
        with a recent version of the CDK CLI.
